name: 'Update Scheduler Task Definition Revisions'
description: 'Used to update all task definition revisions within a scheduler group'
inputs:
  region:
    description: 'Region the scheduler goup is in'
    required: true
  group_name:
    description: 'Name of the scheduler goup'
    required: true
  new_task_definition_arn:
    description: 'ARN of the new task definition revision'
    required: true
  exceptions:
    description: 'Names of any schedules to exclude from the update'
    required: false
runs:
  using: 'node20'
  main: 'index.js'